// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Space = __t.object("Space", {
  id: __t.string(),
  text: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  updatedBy: __t.identity(),
});
export type Space = __Infer<typeof Space>;

