// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ApplyTextOperationReducer from "../apply_text_operation_reducer";
import CreateSpaceReducer from "../create_space_reducer";
import UpdateSpaceTextReducer from "../update_space_text_reducer";

export type ApplyTextOperationParams = __Infer<typeof ApplyTextOperationReducer>;
export type CreateSpaceParams = __Infer<typeof CreateSpaceReducer>;
export type UpdateSpaceTextParams = __Infer<typeof UpdateSpaceTextReducer>;

